server:
    port: 8080


spring:
    datasource:
        url: jdbc:mysql://localhost:3306/BUPT_IOT?characterEncoding=UTF-8&useSSL=false
#        url: jdbc:mysql://118.190.202.148:3306/BUPT_IOT?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: admin123
#        password: Gantch815
        driver-class-name: com.mysql.jdbc.Driver

mybatis:
    mapper-locations: classpath:mappers/*.xml
    type-aliases-package:  com.edu.bupt.wechatpost.model


